version: '3.5'

services:
  postgis:
    image: postgis/postgis:11-2.5-alpine
    restart: always
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
    - /POSTGRES_DATA:/var/lib/postgresql/data/
    - postgresRun:/var/run/postgresql
  osmimport:
    image: osmimport
    restart: always
    pid:
      service:maps2
    depends_on: [maps2,postgis]
    volumes:
     - /MAPS_DATA:/data
     - ./:/work/maps:ro
     - postgresRun:/var/run/postgresql
  maps2:
    image: mapnik2
    depends_on: [postgis]
    restart: always
    volumes:
     - ./:/work/maps:ro
     - ./docker-mapnik/etc:/etc/nginx/sites-enabled
     - /MAPS_DATA:/data
     - /TILESTACHE:/tmp/stache
     - postgresRun:/var/run/postgresql

volumes:
   postgresRun:
