version: '3.5'
# for testing purposes
services:
  postgis:
    image: postgis/postgis:11-2.5-alpine
    restart: always
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
    - /POSTGRES_DATA:/var/lib/postgresql/data/
    - postgresRun:/var/run/postgresql
  osmimport:
    build: docker-osmimport
    restart: always
    pid:
      service:maps
    depends_on: [maps,postgis]
    volumes:
     - /MAPS_DATA:/data
     - ./:/work/maps:ro
     - postgresRun:/var/run/postgresql
  maps:
    ports:
      - 8080:80
    build: docker-mapnik
    depends_on: [postgis]
    restart: always
    volumes:
     - ./:/work/maps:ro
     - ./docker-mapnik/etc:/etc/nginx/sites-enabled
     - /MAPS_DATA:/data
     - /TILESTACHE:/tmp/stache
     - postgresRun:/var/run/postgresql

volumes:
   postgresRun:
